version: "3.7"
services:
  app:
    build: .
    restart: always
    privileged: true
    network_mode: "host"
    volumes:
      - /dev:/dev
    logging:
      options:
        max-size: 10m
  prometheus:
    image: prom/prometheus:latest
    restart: always 
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"
    logging:
      options:
        max-size: 10m

  grafana:
    image: grafana/grafana:6.6.0-beta1
    environment:
      GF_RENDERING_SERVER_URL: http://localhost:8081/render
      GF_RENDERING_CALLBACK_URL: http://localhost:3000/
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    network_mode: "host"
    logging:
      options:
        max-size: 10m

  renderer:
    image: adejong/grafana-image-renderer-pi:1.0.8-beta2
    network_mode: "host"
    logging:
      options:
        max-size: 10m

volumes:
    grafana_data:
